# Generated by Django 4.1 on 2023-12-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentdetail_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
