# Generated by Django 4.1 on 2023-12-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_delete_studentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
